### ISSUE TITLE
Sending email

### ISSUE THREAD

**Issue by jackpeters667** [av1shek/av1shek.github.io#1]
For the Jarvis program, Pretty cool stuff. Sending an email doesn't work for me though. I'm not sure why you're hardcoding the email in like 156 if you want the program to search for it based on the contents of the contacts array. For me, using your code, I just get "send email to adam" then it goes back to "listening", without anything sent. Please explain?

**Comment by av1shek** [comment]
> For the Jarvis program, Pretty cool stuff. Sending an email doesn't work for me though. I'm not sure why you're hardcoding the email in like 156 if you want the program to search for it based on the contents of the contacts array. For me, using your code, I just get "send email to adam" then it goes back to "listening", without anything sent. Please explain?

Ya that is wrong i just forgot to remove the line after debugging my code,
It will goes back to "listening", without anything sent or without any error message when the name is not persent in contact list once check that those names are persent in your contact list array or not.
I think it will work well when you will remove that line, let me know if problem persists and make sure that for gmail account which you are using to login Google SMTP server has "Allow less secure apps: ON" should be enabled.
[Click Here](https://myaccount.google.com/lesssecureapps) to enable "Allow less secure apps: ON".

**Comment by av1shek** [comment]
Closed due to no response.
